import {
  IconAlignBoxLeftStretch,
  IconAnchor,
  IconBrandCss3,
  IconBrandOauth,
  IconBrandReact,
  IconBubbleText,
  IconCameraPlus,
  IconClipboard,
  IconClock,
  IconCloudLock,
  IconCrop,
  IconExchange,
  IconFile,
  IconFileDiff,
  IconFileInfo,
  IconForms,
  IconGrain,
  IconHash,
  IconHierarchy,
  IconHtml,
  IconId,
  IconLine,
  IconLink,
  IconMarkdown,
  IconMenuDeep,
  IconMultiplier1x,
  IconPaint,
  IconPalette,
  IconPdf,
  IconPhotoEdit,
  IconPhotoScan,
  IconPingPong,
  IconProgressDown,
  IconQrcode,
  IconRegex,
  IconScan,
  IconSort09,
  IconSql,
  IconStar,
  IconSvg,
  IconTableAlias,
  IconTicTac,
  IconWand,
  IconWorldWww,
  IconYinYang,
} from "@tabler/icons-react";

import { NavItem } from ".";
import {
  Binoculars,
  DataProtection,
  Electricity,
  MindMap,
  Package,
  Picture,
  Safe,
  SerialTask,
  Shop,
  Transit,
} from "./ColorIcons";

export const navitems: NavItem[] = [
  {
    id: "rest",
    to: "/rest",
    icon: <IconWorldWww />,
    text: "REST API",
    group: "Web",
  },
  {
    id: "epoch",
    to: "/epoch",
    icon: <IconClock />,
    text: "Epoch Converter",
    group: "Web",
  },
  {
    id: "ping",
    to: "/ping",
    icon: <IconPingPong />,
    text: "Ping",
    group: "Utilities",
  },
  {
    id: "password",
    to: "/password",
    icon: <IconGrain />,
    text: "Password Generator",
    group: "Password",
  },
  {
    id: "qrcode",
    to: "/qrcode",
    icon: <IconQrcode />,
    text: "QR Code Generator",
    group: "Generators",
  },
  {
    id: "qrcode-reader",
    to: "/qrcode-reader",
    icon: <IconScan />,
    text: "QR Code Reader",
    group: "Image",
  },
  {
    id: "minify",
    to: "/minify",
    icon: <IconMenuDeep />,
    text: "Minify/Beautify",
    group: "Minifier/Formatters",
  },
  {
    id: "playground",
    to: "/playground",
    icon: <IconBrandReact />,
    text: "React Pad",
    group: "Testing",
  },
  {
    id: "cssplayground",
    to: "/cssplayground",
    icon: <IconBrandCss3 />,
    text: "CSS Playground",
    group: "Testing",
  },
  {
    id: "lorem",
    to: "/lorem",
    icon: <IconForms />,
    text: "Lorem Ipsum",
    group: "Generators",
  },
  {
    id: "image",
    to: "/image",
    icon: <IconPhotoEdit />,
    text: "Image Compressor",
    group: "Image",
  },
  {
    id: "image-crop",
    to: "/image-crop",
    icon: <IconCrop />,
    text: "Image Cropper",
    group: "Image",
  },
  {
    id: "pastebin",
    to: "/pastebin",
    icon: <IconClipboard />,
    text: "Pastebin",
    group: "Utilities",
  },
  {
    id: "repl",
    to: "/repl",
    icon: <IconAlignBoxLeftStretch />,
    text: "Scratchpad",
    group: "Testing",
  },
  {
    id: "bulk-image",
    to: "/bulk-image",
    icon: <IconCameraPlus />,
    text: "Bulk Compressor",
    group: "Image",
  },
  {
    id: "base64-text",
    to: "/base64-text",
    icon: <IconBubbleText />,
    text: "Base64 Text",
    group: "Converters",
  },
  {
    id: "base64-image",
    to: "/base64-image",
    icon: <IconPhotoScan />,
    text: "Base64 Image",
    group: "Converters",
  },
  {
    id: "hash-text",
    to: "/hash-text",
    icon: <IconHash />,
    text: "Hashing Text",
    group: "Hashing",
  },
  {
    id: "hash-file",
    to: "/hash-file",
    icon: <IconFile />,
    text: "Hashing Files",
    group: "Hashing",
  },
  {
    id: "hmac-generator",
    to: "/hmac-generator",
    icon: <IconTicTac />,
    text: "HMAC Generator",
    group: "Hashing",
  },
  {
    id: "json-formatter",
    to: "/json-formatter",
    icon: <IconAnchor />,
    text: "JSON Tools",
    group: "Minifier/Formatters",
  },
  {
    id: "jwt",
    to: "/jwt",
    icon: <IconBrandOauth />,
    text: "JWT Tools",
    group: "Web",
  },
  {
    id: "nums",
    to: "/nums",
    icon: <IconSort09 />,
    text: "Number Tools",
    group: "Converters",
  },
  {
    id: "sql",
    to: "/sql",
    icon: <IconSql />,
    text: "SQL Formatter",
    group: "Minifier/Formatters",
  },
  {
    id: "colors",
    to: "/colors",
    icon: <IconWand />,
    text: "Color Utils",
    group: "Converters",
  },
  {
    id: "harmonies",
    to: "/harmonies",
    icon: <IconPalette />,
    text: "Harmonies",
    group: "Generators",
  },
  {
    id: "color-testing",
    to: "/color-testing",
    icon: <IconPaint />,
    text: "Color Testing",
    group: "Testing",
  },
  {
    id: "diff",
    to: "/diff",
    icon: <IconFileDiff />,
    text: "Diff Tools",
    group: "Utilities",
  },
  {
    id: "text",
    to: "/text",
    icon: <IconMultiplier1x />,
    text: "Text Analysis",
    group: "Utilities",
  },
  {
    id: "snippets",
    to: "/snippets",
    icon: <IconFileInfo />,
    text: "Snippets",
    group: "Utilities",
  },
  {
    id: "markdown",
    to: "/markdown",
    icon: <IconMarkdown />,
    text: "Markdown",
    group: "Previewers",
  },
  {
    id: "readme",
    to: "/readme",
    icon: <IconFileInfo />,
    text: "Readme",
    group: "Generators",
  },
  {
    id: "yamljson",
    to: "/yamljson",
    icon: <IconYinYang />,
    text: "Yaml Json",
    group: "Converters",
  },
  {
    id: "units",
    to: "/units",
    icon: <IconExchange />,
    text: "Unit Converter",
    group: "Converters",
  },
  {
    id: "compress",
    to: "/compress",
    icon: <IconProgressDown />,
    text: "Compress Text",
    group: "Minifier/Formatters",
  },
  {
    id: "stateless",
    to: "/stateless",
    icon: <IconCloudLock />,
    text: "Stateless Password",
    group: "Password",
  },

  {
    id: "quicktype",
    to: "/quicktype",
    icon: <IconHierarchy />,
    text: "Quicktype",
    group: "Testing",
  },

  {
    id: "url-parser",
    to: "/url-parser",
    icon: <IconLink />,
    text: "URL Parser",
    group: "Web",
  },
  {
    id: "url-encoder",
    to: "/url-encoder",
    icon: <IconLine />,
    text: "URL Encoder",
    group: "Web",
  },
  {
    id: "html-preview",
    to: "/html-preview",
    icon: <IconHtml />,
    text: "HTML Preview",
    group: "Previewers",
  },
  {
    id: "svg-preview",
    to: "/svg-preview",
    icon: <IconSvg />,
    text: "SVG Preview",
    group: "Previewers",
  },
  {
    id: "pdf-reader",
    to: "/pdf-reader",
    icon: <IconPdf />,
    text: "PDF Reader",
    group: "Previewers",
  },

  {
    id: "cron",
    to: "/cron",
    icon: <IconStar />,
    text: "Cron",
    group: "Utilities",
  },
  {
    id: "ids",
    to: "/ids",
    icon: <IconId />,
    text: "ID Generator",
    group: "Generators",
  },
  {
    id: "regex",
    to: "/regex",
    icon: <IconRegex />,
    text: "Regex Tester",
    group: "Testing",
  },
  {
    id: "faker",
    to: "/faker",
    icon: <IconTableAlias />,
    text: "Faker",
    group: "Generators",
  },
];

export const groupIcons = {
  Web: <Package />,
  Utilities: <Transit />,
  Testing: <DataProtection />,
  Password: <Safe />,
  Image: <Picture />,
  Generators: <Shop />,
  "Minifier/Formatters": <MindMap />,
  Previewers: <Binoculars />,
  Converters: <Electricity />,
  Hashing: <SerialTask />,
};
